version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'actone'
      MYSQL_USER: 'actone'
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_PASSWORD: '123'
    ports:
      - '3305:3306'
    expose:
      - '3305'
    volumes:
      - actone_mysql:/var/lib/mysql

volumes:
  actone_mysql: